### ISSUE TITLE
[SUGGESTION] Discord Rich Presence for Custom Files

### ISSUE THREAD

**Issue by ENTPRESTIGIOUS** [LeonardSSH/vscord#13]
Hello! I would like to know if it is possible to create presences for files that have a custom extension to the file such as .drawio or anything else.

**Comment by LeonardSSH** [comment]
At the code level, this is not possible because, the RPC when connecting to the Discord Gateway, it connects through an ID, which that id has its icons, I cannot use icons from another ID without starting the RPC with that ID. 

If you want support for other extensions than the existing ones, give me the icon and I will process and add it.
