### ISSUE TITLE
Should language be more important then file extension?

### ISSUE THREAD

**Issue by MiguelNdeCarvalho** [LeonardSSH/vscord#46]
Hey,

For example when I am messing with ansible, name of the file `main.yml` the plugin will show that I'm editing a **YAML** file instead of **Ansible** file. But the language of the file is **Ansible**. Is is possible to give priority to the Language?

Thanks,
MiguelNdeCarvalho

**Comment by LeonardSSH** [comment]
I'll add a config property in this case, because probably some users don't want languages to be prioritized over extensions.

I also added the icon for Ansible.

<details>
   <summary>Show Icon</summary>

![image](https://user-images.githubusercontent.com/35312043/148144642-ef6310e7-96c7-4e9d-9f8e-4c3924c7941d.png)

</details>

**Comment by MiguelNdeCarvalho** [comment]
I totally agree with you, thanks!
