### ISSUE TITLE
package.json

### ISSUE THREAD

**Issue by Tazi0** [LeonardSSH/vscord#54]
<img width="231" alt="Screen Shot 2022-02-04 at 21 02 18" src="https://user-images.githubusercontent.com/45716542/152596042-9fc2795f-5db4-4b4d-87dc-1a188a50d195.png">
Currently the file is shown as a JSON, but i suggest making it a npm icon. Couldn’t seem to get it to work but it shouldn’t be a biggy

**Comment by LeonardSSH** [comment]
@Tazi0 have you upgraded the extension to the latest version? 

Make sure that `rpc.prioritizeLanguagesOverExtensions` is set to `false`, otherwise it will prioritize the language over the extension

![image](https://user-images.githubusercontent.com/35312043/152822047-e687ef98-dc09-4843-a13b-d0f695b05c09.png)
Works for me

**Comment by Tazi0** [comment]
there we go 👍🏻 i will let you know if i got more ideas!
